version: "3.5"
networks:
  ripple_testnet:
    external : true
    name: ${TESTNET:-"ripple-testnet"}

volumes:
  grafana-data:
    external : true
    name: ${GF_DATA_VOL_NAME:-testnet_grafana_data}
  influxdb-data:
    external : true
    name: ${INFLUXDB_VOL_NAME:-testnet_influxdb_data}
  prometheus-data:
    external : true
    name: ${PROM_DATA_VOL_NAME:-testnet_prometheus_data}

services:
  influxdb:
    image: influxdb:1.8.1
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=ripple
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-iff_user}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-iff_psw}
    networks:
      - ripple_testnet
    volumes:
      # - ./local_bind_volume_dir:/var/lib/influxdb 
      - influxdb-data:/var/lib/influxdb

    ports:
      - 8086:8086
  pushgateway:
    image: prom/pushgateway:${PUSHGW_IMG_TAG:-latest}
#    image: prom/pushgateway:${PUSHGW_IMG_TAG:-v0.4.0
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - ripple_testnet
  prometheus:
    image: prom/prometheus:v2.0.0
#    image: prom/prometheus:v2.0.0
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - ripple_testnet
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/
      - prometheus-data:/prometheus/data
  grafana:
    image: grafana/grafana:${GRAFANA_IMG_TAG:-latest}
    container_name: grafana
#    image: grafana/grafana:4.6.2
    ports:
      - 3000:3000
    networks:
      - ripple_testnet
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      # - GF_PATHS_CONFIG=/opt/grafana-config/grafana.ini
    volumes:
      - grafana-data:/var/lib/grafana
      # - ./grafana-storage/grafana-data:/var/lib/grafana # didn't work because of permissions
      # USE the following in combination with env GF_PATHS_CONFIG=/opt/grafana-config/grafana.ini
      # - ./grafana-storage/config:/opt/grafana-config 
    
  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_IMG_TAG:-latest}
    container_name: alertmanager
#    image: prom/alertmanager:v0.11.0
    command: --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - ripple_testnet
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  docker_stats_exporter:
    image: wywywywy/docker_stats_exporter:latest
    container_name: dc_stats_exp
    ports:
      - 9487:9487
    networks: 
      - ripple_testnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
