version: "3.5"

networks:
  ripple-testnet:
    external: true
    name: ${MYTESTNET:-"ripple-testnet"}

services:
  rippled-traffic-gen:
#    image: node:12
    image: uniciff/ripple-traffic-gen:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: rippled-traffic-gen
    volumes:
      - .:/home/node/rtg
    networks:
      - ripple-testnet
    #entrypoint: /bin/bash
    tty: true
    working_dir: /home/node/rtg


